_base_: ../base.yaml

project:
  output_dir: outputs/dual_4090

backend:
  kind: vllm
  model: /home/fyk/models/Qwen/Qwen2.5-X.XB-Instruct
  model_size: 7B
  base_url: http://127.0.0.1:8000/v1
  api_key: EMPTY
  extra_body:
    top_k: 40

serving:
  enabled: true
  kind: vllm
  model_name_or_path: /home/fyk/models/Qwen/Qwen2.5-X.XB-Instruct
  model_size: 7B
  gpu_ids: [0] # [0,1]
  tensor_parallel_size: 1 #2
  host: 127.0.0.1
  port: 8000
  api_key: EMPTY
  dtype: auto
  gpu_memory_utilization: 0.92
  max_model_len: 4096
  max_num_seqs: 16

training:
  model_name_or_path: /home/fyk/models/Qwen/Qwen2.5-X.XB-Instruct
  model_size: 7B
  mode: lora
  high_credit_threshold: 0.65
  distributed:
    gpus: [0] # [0,1]
    nproc_per_node: 1 #2
    nnodes: 1
    node_rank: 0
    master_addr: 127.0.0.1
    master_port: 29500
    force_torchrun: true
