"""
Training execution engine.

Calls LLaMA-Factory via subprocess to run SFT, DPO, and merge operations.
Designed for Qwen2.5 + dual RTX 4090 environment.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any

from cegsr.utils.io import ensure_dir, write_json
from cegsr.utils.logging import get_logger

logger = get_logger(__name__)


class TrainingError(RuntimeError):
    """Raised when a LLaMA-Factory training job fails."""


def _run_llamafactory_cli(
    subcommand: str,
    config_path: str,
    env_overrides: dict[str, str] | None = None,
    timeout: int | None = None,
) -> subprocess.CompletedProcess[str]:
    """Run ``llamafactory-cli <subcommand> <config>`` and stream output."""
    import os
    env = {**os.environ, **(env_overrides or {})}
    cmd = ["llamafactory-cli", subcommand, config_path]
    logger.info("Running: %s", " ".join(cmd))
    result = subprocess.run(
        cmd,
        env=env,
        text=True,
        timeout=timeout,
    )
    if result.returncode != 0:
        raise TrainingError(
            f"llamafactory-cli {subcommand} failed (exit {result.returncode}): {config_path}"
        )
    return result


def _build_env_for_distributed(distributed_config: dict[str, Any]) -> dict[str, str]:
    """Build environment variables for distributed training."""
    env: dict[str, str] = {}
    gpus = distributed_config.get("gpus")
    if gpus:
        if isinstance(gpus, (list, tuple)):
            env["CUDA_VISIBLE_DEVICES"] = ",".join(str(g) for g in gpus)
        else:
            env["CUDA_VISIBLE_DEVICES"] = str(gpus)
    if distributed_config.get("force_torchrun", True):
        env["FORCE_TORCHRUN"] = "1"
    env["NNODES"] = str(distributed_config.get("nnodes", 1))
    env["NODE_RANK"] = str(distributed_config.get("node_rank", 0))
    nproc = distributed_config.get("nproc_per_node")
    if nproc is None and gpus:
        nproc = len(env["CUDA_VISIBLE_DEVICES"].split(","))
    env["NPROC_PER_NODE"] = str(nproc or 1)
    env["MASTER_ADDR"] = str(distributed_config.get("master_addr", "127.0.0.1"))
    env["MASTER_PORT"] = str(distributed_config.get("master_port", 29500))
    return env


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def run_sft(
    config_path: str,
    distributed_config: dict[str, Any] | None = None,
    timeout: int | None = None,
) -> str:
    """
    Run SFT training via LLaMA-Factory.

    Args:
        config_path: Path to the LLaMA-Factory YAML config (generated by adapter).
        distributed_config: Optional distributed training env vars.
        timeout: Max seconds to wait (None = no limit).

    Returns:
        output_dir from the config (where adapter is saved).
    """
    import yaml
    cfg = yaml.safe_load(Path(config_path).read_text(encoding="utf-8"))
    output_dir = cfg.get("output_dir", "")
    logger.info("SFT training: config=%s output=%s", config_path, output_dir)

    env = _build_env_for_distributed(distributed_config) if distributed_config else None
    _run_llamafactory_cli("train", config_path, env_overrides=env, timeout=timeout)

    logger.info("SFT training complete: %s", output_dir)
    return output_dir


def run_dpo(
    config_path: str,
    distributed_config: dict[str, Any] | None = None,
    timeout: int | None = None,
) -> str:
    """
    Run DPO training via LLaMA-Factory.

    Args:
        config_path: Path to the DPO YAML config.
        distributed_config: Optional distributed training env vars.
        timeout: Max seconds to wait (None = no limit).

    Returns:
        output_dir from the config.
    """
    import yaml
    cfg = yaml.safe_load(Path(config_path).read_text(encoding="utf-8"))
    output_dir = cfg.get("output_dir", "")
    logger.info("DPO training: config=%s output=%s", config_path, output_dir)

    env = _build_env_for_distributed(distributed_config) if distributed_config else None
    _run_llamafactory_cli("train", config_path, env_overrides=env, timeout=timeout)

    logger.info("DPO training complete: %s", output_dir)
    return output_dir


def merge_lora(
    config_path: str,
) -> str:
    """
    Merge LoRA adapter into base model via LLaMA-Factory export.

    Returns:
        export_dir (path to the merged model).
    """
    import yaml
    cfg = yaml.safe_load(Path(config_path).read_text(encoding="utf-8"))
    export_dir = cfg.get("export_dir", "")
    logger.info("Merging LoRA: config=%s output=%s", config_path, export_dir)

    _run_llamafactory_cli("export", config_path)

    logger.info("LoRA merge complete: %s", export_dir)
    return export_dir


def run_training_pipeline(
    export_dir: str,
    training_mode: str = "lora",
    run_dpo_stage: bool = False,
    merge_after_training: bool = True,
    distributed_config: dict[str, Any] | None = None,
    timeout_per_stage: int | None = None,
) -> dict[str, str]:
    """
    Execute the full training pipeline: SFT → (optional DPO) → (optional merge).

    Args:
        export_dir: Directory with generated LLaMA-Factory configs (from adapter).
        training_mode: "lora" or "qlora".
        run_dpo_stage: Whether to run DPO after SFT.
        merge_after_training: Whether to merge the final adapter into base model.
        distributed_config: Optional distributed training config.
        timeout_per_stage: Max seconds per training stage.

    Returns:
        Dict with paths: {"sft_adapter", "dpo_adapter" (optional), "merged_model" (optional)}.
    """
    export_path = Path(export_dir)
    results: dict[str, str] = {}

    # Stage 1: SFT (combined adapter - all roles)
    sft_config = export_path / f"llamafactory_combined_{training_mode}.yaml"
    if not sft_config.exists():
        # Fallback: find any SFT config
        candidates = sorted(export_path.glob(f"llamafactory_*_{training_mode}.yaml"))
        candidates = [c for c in candidates if "dpo" not in c.name and "merge" not in c.name]
        if not candidates:
            raise TrainingError(f"No SFT config found for mode '{training_mode}' in {export_dir}")
        sft_config = candidates[0]
        logger.warning("Combined config not found, using: %s", sft_config)

    sft_output = run_sft(str(sft_config), distributed_config=distributed_config, timeout=timeout_per_stage)
    results["sft_adapter"] = sft_output

    # Stage 2: DPO (optional)
    if run_dpo_stage:
        dpo_config = export_path / "llamafactory_dpo.yaml"
        if dpo_config.exists():
            dpo_output = run_dpo(str(dpo_config), distributed_config=distributed_config, timeout=timeout_per_stage)
            results["dpo_adapter"] = dpo_output
        else:
            logger.warning("DPO config not found, skipping DPO stage")

    # Stage 3: Merge (optional)
    if merge_after_training:
        merge_config = export_path / "llamafactory_merge.yaml"
        if merge_config.exists():
            merged_path = merge_lora(str(merge_config))
            results["merged_model"] = merged_path
        else:
            logger.warning("Merge config not found, skipping merge")

    # Save results
    write_json(export_path / "training_results.json", results)
    logger.info("Training pipeline complete: %s", results)
    return results
